//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendanceDbEntities : DbContext
    {
        public AttendanceDbEntities()
            : base("name=AttendanceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M101User> M101_USER { get; set; }
        public virtual DbSet<M102UserAuth> M102_USER_AUTH { get; set; }
        public virtual DbSet<M103UserDepartment> M103_USER_DEPARTMENT { get; set; }
        public virtual DbSet<M201CodeMst> M201_CODE_MST { get; set; }
        public virtual DbSet<V103UserDepartment> V103_USER_DEPARTMENT { get; set; }
        public virtual DbSet<T200AttendanceTime> T200_ATTENDANCE_TIME { get; set; }
        public virtual DbSet<V200AttendanceTime> V200_ATTENDANCE_TIME { get; set; }
    }
}
