//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class M101User
    {
        public string UserId { get; set; }
        public string USER_NAME { get; set; }
        public string DELETE_FLG { get; set; }
        public System.DateTime CREATE_DT { get; set; }
        public System.DateTime UPDATE_DT { get; set; }
        public string UPDATE_USER_ID { get; set; }
    }
}
