//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class M201CodeMst
    {
        public string CdKind { get; set; }
        public string Cd { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
    }
}
