//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は必須項目です。入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MEI0001 {
            get {
                return ResourceManager.GetString("MEI0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0]は{1}文字以内で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MEI0002 {
            get {
                return ResourceManager.GetString("MEI0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーIDまたはパスワードが正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MEP0003 {
            get {
                return ResourceManager.GetString("MEP0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}のデータは他のユーザーにより更新されています。再度ログインを行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MEP0004 {
            get {
                return ResourceManager.GetString("MEP0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正なアクセスです。ログイン画面から再度アクセスしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MEP0005 {
            get {
                return ResourceManager.GetString("MEP0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   予期しないエラーが発生しました。最初からやり直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MEP0006 {
            get {
                return ResourceManager.GetString("MEP0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面を表示する権限がありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MEP0007 {
            get {
                return ResourceManager.GetString("MEP0007", resourceCulture);
            }
        }
    }
}
